### ISSUE TITLE
todo before first release

### ISSUE THREAD

**Issue by girardinsamuel** [girardinsamuel/blog#36]
- [ ] ajout page projet détail
- [ ] ajout labels (badges) projets => planned, in dev, released
- [ ] finalisation page about
- [ ] écriture 1 ou 2 articles laravel mix with masonite, Vue3 with masonite + Tailwind CSS. Demo of inertia ?
- [ ] détail projet masonite-admin qq screenshots
- [ ]
